CREATE TABLE DM_CP_CUSTOMER (
  CUSTOMER_ID NUMBER NOT NULL,
  CUSTOMER_CODE VARCHAR2(16) NOT NULL,
  DISPLAY_NAME VARCHAR2(80) NOT NULL,
  STATUS_CODE VARCHAR2(12) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT DM_CP_CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT DM_CP_CUSTOMER_CODE_UK UNIQUE (CUSTOMER_CODE),
  CONSTRAINT DM_CP_CUSTOMER_STATUS_CK CHECK (STATUS_CODE IN ('ACTIVE', 'INACTIVE'))
);
