CREATE OR REPLACE EDITIONABLE FUNCTION DM_CP_LABEL (P_CUSTOMER_CODE IN VARCHAR2)
RETURN VARCHAR2
AS
  V_LABEL VARCHAR2(100);
BEGIN
  SELECT CUSTOMER_CODE || ':' || DISPLAY_NAME INTO V_LABEL
    FROM DM_CP_CUSTOMER WHERE CUSTOMER_CODE = P_CUSTOMER_CODE;
  RETURN V_LABEL;
END;
/
