INSERT INTO DM_CP_CUSTOMER (CUSTOMER_ID, CUSTOMER_CODE, DISPLAY_NAME, STATUS_CODE)
VALUES (DM_CP_CUSTOMER_SEQ.NEXTVAL, 'C0001', 'Demo Customer One', 'ACTIVE');
INSERT INTO DM_CP_CUSTOMER (CUSTOMER_ID, CUSTOMER_CODE, DISPLAY_NAME, STATUS_CODE)
VALUES (DM_CP_CUSTOMER_SEQ.NEXTVAL, 'C0002', 'Demo Customer Two', 'ACTIVE');
INSERT INTO DM_CP_CUSTOMER (CUSTOMER_ID, CUSTOMER_CODE, DISPLAY_NAME, STATUS_CODE)
VALUES (DM_CP_CUSTOMER_SEQ.NEXTVAL, 'C0003', 'Demo Customer Three', 'INACTIVE');
