-- Reviewed correction: DEV already has this synthetic index; other stages do not.
DECLARE
  V_COUNT PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES
    WHERE INDEX_NAME = 'DM_CP_CUSTOMER_REGION_IX';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DM_CP_CUSTOMER_REGION_IX ON DM_CP_CUSTOMER (DISPLAY_NAME)';
  END IF;
END;
/
