BEGIN
  IF SYS_CONTEXT('USERENV','CURRENT_SCHEMA') = 'ODC_POC_20261004_SIT' THEN
    RAISE_APPLICATION_ERROR(-20007, 'P7 controlled SIT failure before CREATE');
  END IF;
END;
/
CREATE TABLE P7_BATCH_FAIL (ID NUMBER PRIMARY KEY);
